// Code generated by envschema. DO NOT EDIT.

package config

import (
	"encoding/json"
	custom "github.com/depthbomb/envschema/example/config/schema"
	"time"

	"github.com/depthbomb/envschema"
)

var generatedSchema = envschema.Must(
	envschema.Var("DATABASE_URL", envschema.URL()),
	envschema.Var("PORT", envschema.Port().DefaultTo(json.Number("8080"))),
	envschema.Var("DEBUG", envschema.Boolean().Optional()),
	envschema.Var("REQUEST_TIMEOUT", envschema.Duration().DefaultTo("5s")),
	envschema.Var("ALLOWED_HOSTS", envschema.List(envschema.Host()).UniqueItems()),
	envschema.Var("API_TOKEN", envschema.Secret()),
	envschema.Var("LOG_LEVEL", envschema.CustomNamed("github.com/depthbomb/envschema/example/config/schema", "LogLevel").DefaultTo("info")),
)

type Config struct {
	DatabaseUrl    string                `env:"DATABASE_URL"`
	Port           int64                 `env:"PORT"`
	Debug          *bool                 `env:"DEBUG"`
	RequestTimeout time.Duration         `env:"REQUEST_TIMEOUT"`
	AllowedHosts   []string              `env:"ALLOWED_HOSTS"`
	ApiToken       envschema.SecretValue `env:"API_TOKEN"`
	LogLevel       custom.LogLevel       `env:"LOG_LEVEL"`
}

func LoadFrom(lookup envschema.LookupFunc) (Config, error) {
	var config Config
	var failures []error
	value0, _, err := envschema.Read[string](generatedSchema.Variables[0].Rule, "DATABASE_URL", lookup)
	if err != nil {
		failures = append(failures, err)
	}
	config.DatabaseUrl = value0
	value1, _, err := envschema.Read[int64](generatedSchema.Variables[1].Rule, "PORT", lookup)
	if err != nil {
		failures = append(failures, err)
	}
	config.Port = value1
	value2, present2, err := envschema.Read[bool](generatedSchema.Variables[2].Rule, "DEBUG", lookup)
	if err != nil {
		failures = append(failures, err)
	}
	if present2 {
		config.Debug = &value2
	}
	value3, _, err := envschema.Read[time.Duration](generatedSchema.Variables[3].Rule, "REQUEST_TIMEOUT", lookup)
	if err != nil {
		failures = append(failures, err)
	}
	config.RequestTimeout = value3
	value4, _, err := envschema.Read[[]string](generatedSchema.Variables[4].Rule, "ALLOWED_HOSTS", lookup)
	if err != nil {
		failures = append(failures, err)
	}
	config.AllowedHosts = value4
	value5, _, err := envschema.Read[envschema.SecretValue](generatedSchema.Variables[5].Rule, "API_TOKEN", lookup)
	if err != nil {
		failures = append(failures, err)
	}
	config.ApiToken = value5
	value6, _, err := envschema.ReadText[custom.LogLevel](generatedSchema.Variables[6].Rule, "LOG_LEVEL", lookup)
	if err != nil {
		failures = append(failures, err)
	}
	config.LogLevel = value6
	if err := envschema.JoinErrors(failures...); err != nil {
		return Config{}, err
	}

	return config, nil
}

func Load() (Config, error) {
	lookup, err := envschema.LookupEnvFiles()
	if err != nil {
		return Config{}, err
	}

	return LoadFrom(lookup)
}

func LoadSource(input envschema.Source, prefixes ...string) (Config, error) {
	if err := envschema.ValidateKnownVariables(generatedSchema, input, prefixes...); err != nil {
		return Config{}, err
	}
	return LoadFrom(input.Lookup)
}

func LoadWithReport(input envschema.Source) (Config, envschema.LoadReport, error) {
	values, report, err := envschema.LoadWithReport(generatedSchema, input)
	if err != nil {
		return Config{}, report, err
	}
	var config Config
	var failures []error
	if _, present := values["DATABASE_URL"]; present {
		value, err := envschema.ValueAs[string](values, "DATABASE_URL")
		if err != nil {
			failures = append(failures, err)
		} else {
			config.DatabaseUrl = value
		}
	}
	if _, present := values["PORT"]; present {
		value, err := envschema.ValueAs[int64](values, "PORT")
		if err != nil {
			failures = append(failures, err)
		} else {
			config.Port = value
		}
	}
	if _, present := values["DEBUG"]; present {
		value, err := envschema.ValueAs[bool](values, "DEBUG")
		if err != nil {
			failures = append(failures, err)
		} else {
			config.Debug = &value
		}
	}
	if _, present := values["REQUEST_TIMEOUT"]; present {
		value, err := envschema.ValueAs[time.Duration](values, "REQUEST_TIMEOUT")
		if err != nil {
			failures = append(failures, err)
		} else {
			config.RequestTimeout = value
		}
	}
	if _, present := values["ALLOWED_HOSTS"]; present {
		value, err := envschema.ValueAs[[]string](values, "ALLOWED_HOSTS")
		if err != nil {
			failures = append(failures, err)
		} else {
			config.AllowedHosts = value
		}
	}
	if _, present := values["API_TOKEN"]; present {
		value, err := envschema.ValueAs[envschema.SecretValue](values, "API_TOKEN")
		if err != nil {
			failures = append(failures, err)
		} else {
			config.ApiToken = value
		}
	}
	if _, present := values["LOG_LEVEL"]; present {
		value, _, err := envschema.ReadText[custom.LogLevel](generatedSchema.Variables[6].Rule, "LOG_LEVEL", func(name string) (string, bool) {
			value, present := values[name].(string)

			return value, present
		})
		if err != nil {
			failures = append(failures, err)
		} else {
			config.LogLevel = value
		}
	}
	if err := envschema.JoinErrors(failures...); err != nil {
		return Config{}, report, err
	}
	return config, report, nil
}
